In [2]:
import numpy as np

### Q1. Create a NumPy array of 10 random integers between 1 and 100. Find its mean. 

In [12]:
arr = np.random.randint(1, 101, 10)
arr

array([36, 89, 39, 63, 26, 29, 66, 51, 69, 94], dtype=int32)

In [13]:
arr.mean()

np.float64(56.2)

### Q2. Calculate the median of the array: [10, 5, 8, 12, 3, 7]. 


In [13]:
arr = np.array([10, 5, 8, 12, 3, 7])
arr

array([10,  5,  8, 12,  3,  7])

In [18]:
median = np.median(arr)
median

np.float64(7.5)

### Q3. Generate an array of 15 random numbers between 1 and 50. Find its standard deviation. 


In [16]:
arr = np.random.randint(1, 51, 15)   # 15 random integers from 1 to 50
arr

array([31,  7,  4, 31, 44, 47, 26, 18,  2, 38, 12,  7,  9, 27, 27],
      dtype=int32)

In [17]:
arr.size

15

In [18]:
std = np.std(arr)
std

np.float64(14.264174237111192)

### Q4. Create a 3x3 array with values from 1 to 9. Find the row-wise mean. 


In [41]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr.resize(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
row_wise_mean = arr.mean(axis=1)
row_wise_mean

array([2., 5., 8.])

### Q5. For the array [4, 6, 8, 10, 12], calculate mean, median, std. 


In [46]:
import numpy as np

In [49]:
arr = np.array([4, 6, 8, 10, 12])
arr

array([ 4,  6,  8, 10, 12])

In [51]:
mean = arr.mean()
mean

np.float64(8.0)

In [52]:
median = np.median(arr)
median

np.float64(8.0)

In [55]:
std_dev = np.std(arr)
std_dev

np.float64(2.8284271247461903)

### Q6. Generate a 5x5 NumPy array of random integers (0 to 100). Find the overall mean. 


In [64]:
arr = np.random.randint(0, 101, (5, 5))
arr

array([[ 3, 49, 26,  9, 42],
       [ 6, 12, 99, 70, 75],
       [56, 27, 75, 38, 97],
       [33, 18, 29, 33, 86],
       [53, 83, 91, 19, 86]], dtype=int32)

In [14]:
mean = np.mean(arr)
mean

np.float64(56.2)


### Q7. Create an array of 50 random integers and calculate the standard deviation. 


In [71]:
arr = np.random.randint(1, 101, 50)
arr

array([80, 76, 75,  3, 11, 24, 23, 68, 17, 36, 89, 14, 54, 60, 70, 43, 71,
       30, 87, 41, 96,  4, 63, 73, 97, 30, 89, 77,  8,  1, 79, 72,  8, 28,
       49, 37, 93,  2,  2, 82, 60, 59, 32, 45, 21, 98, 64, 21, 80, 88],
      dtype=int32)

In [72]:
std_dev = np.std(arr)
std_dev

np.float64(30.605228311515667)

### Q8. Find indices of non-zero elements from [1,2,0,0,4,0] 


In [73]:
arr = np.array([1,2,0,0,4,0])
arr

array([1, 2, 0, 0, 4, 0])

In [76]:
np.nonzero(arr)

(array([0, 1, 4]),)

### Q9. You have a 2D array, print array element [[7,4]]:
        [[2,3,4  
          5,7,4  
          8,9,0]]  


In [2]:
import numpy as np

In [3]:
arr = np.array([
    [2, 3, 4],
    [5, 7, 4],
    [8, 9, 0]
])
arr

array([[2, 3, 4],
       [5, 7, 4],
       [8, 9, 0]])

In [4]:
# Access element '7' → row=1, col=1
element = arr[1, 1]
element

np.int64(7)

### Q10. Create 2 array of 2-Dimension and then perform matrix multiplication on them. 


In [6]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [10]:
c = a@b
c

array([[19, 22],
       [43, 50]])

In [11]:
# OR
c = np.dot(a,b)
c

array([[19, 22],
       [43, 50]])